### ISSUE TITLE
integration with PackageControl.io

### ISSUE THREAD

**Issue by gour** [bemilton/sublime_zk#2]
Hello,

Any news about integrating the package into [PackageControl](https://packagecontrol.io/)?

Are you still behind the package?

**Comment by bemilton** [comment]
Here's a workaround: Install sublime_zk from PackageControl, but then open up PackageControl settings from Preferences | Package Settings | Package Control | Settings and change the URL of sublime_zk to `https://github.com/bemilton/sublime_zk`.
