### ISSUE TITLE
when using the "make a new note", the syntax is "markdown", not "markdown zettelkasten"

### ISSUE THREAD

**Issue by emilBeBri** [bemilton/sublime_zk#3]
**Describe the bug**
It's very simple, as stated: When using either the command palette or keyboard shortcut to create a new note, the default syntax of the note is markdown. So you have to manually set the syntax to "markdown zettelkasten", so that links work and so on.

**Expected behavior**
I expect the new note to be in the "markdown zettelkasten" syntax

**Console output**
No console output is produced?!

**Desktop (please complete the following information):**
 - OS: Lubuntu Linux 20.04
 - ST version 3.2.2,  build 3211

**Comment by bemilton** [comment]
Can you share your user settings? (Preferences | Package Settings | Sublime_zk)

**Comment by emilBeBri** [comment]
sure thing, here it is:


```
{
    // Toggle whether find_all_tags_in_archive command
    // displays the tag count and orders by most common
    "insert_tag_count": true,

    // Specify CSL style for the bibliography generation.
    "csl_style": "",

    // Interpreter abspath for spacyCountSylls.py if using
    // venv, else system binary.
    "venv_spacy_fk_abspath": "",

    // And the path to fk script in $USER/.config/sublime_zk/Packages
    "spacy_fk_script_abspath": "",

    // The preferred markdown extension
    "wiki_extension": ".md",

    // when creating a new link, use [[double brackets]]
    // false to use [single brackets]
    "double_brackets": true,

    // links like "[[199901012359]] and note title" instead of "[[199901012359]]"
    "insert_links_with_titles": true,
    // and move the title inside the brackets?
    "move_title_inside_brackets": true,

    // when creating a new note, put id into title?
     // false to disable
    "id_in_title": true,

    // highlight links to other notes?
    // false to disable
    "highlight_note_links": true,

    // prefix for #tags
    "tag_prefix": "#",

    // when highlighting: also show bookmark symbols in the gutter?
    // false to disable
    "show_bookmarks_in_gutter": true,

    // should the tag list appear in a new pane right to the note?
    "show_all_tags_in_new_pane": true,

    // show find results in a new tab?
    // false to disable: then they will be displayed at the bottom of the window
    "show_search_results_in_new_tab": true,

    // fall-back: location of ag if it cannot be found in the PATH
    "path_to_ag": "/usr/local/bin/ag",

    // for auto-completion of citekeys and auto-bibs
    // enter the full path to your .bib file here
    "bibfile": "/home/emil/Dropbox/bibliotek/bibliotek.bib",


    // make sure images don't get too large
    // scale them to max_width, proportionally
    "img_maxwidth": 320,

    // set to true if you want images to be displayed automatically when you open a note
    "auto_show_images": false,

    // separator to use when appending numbered suffix to duplicate headings
    // in table of contents. If you use pandoc, change this to a "-".
    "toc_suffix_separator": "_",

    // use multimarkdown style for citations
    // set to false to use pandoc style:
    //    use [@citekey] to reference something in your .bib file
    //    autobib style will be: [@citekey]: full-blown reference
    // set to true to use multimarkdown style:
    //    use [][#citekey] to reference something in your .bib file
    //    autobib style will be: [#citekey]: full-blown reference
    // note: for autobib to work you still need pandoc installed in either case
    "citations-mmd-style": false,

    // Pane where notes are opened when a link is clicked or a new note is created
    // Pane 0 is the 1st pane ever
    "pane_for_opening_notes": 0,
    //Pane where search results and tag lists, etc are opened (if ag is installed)
    // Pane 1 is the second pane, created when you split the window
    //    in a 2-column layout, this is the right column
    //    in a 2-row layout, this is the bottom row
    "pane_for_opening_results": 1,

    // seconds in note IDs?
    // if true : YYYYMMDDHHMMSS 20171224183045
    // if false: YYYYMMDDHHMM   201712241830
    "seconds_in_id": true,

    // Sort note lists (search results) by
    // - title
    // - ID       <-- default
    "sort_notelists_by": "id",

    // set to true to enable super awesome zettelkasten mode
    "zettelkasten_mode" : true,
}
```


Tried reproducing this behaviour with a clean install, what happens is that new zettelkasten notes default syntax is 

"Zettelkasten-Saved-Searches" 
 
 which it also does with any new file with the .md extension produced manually will get. So In some way, in my normal setup, it's changed from this into normal markdown syntax when creating notes, insted of zettelkasten markdown notes. But it seems to be the same issue, I'd say.

I made a video reproducing it here, where the other bug (that I haven't mentioned yet) that is  hindering this beautiful package from it's full potential, also shows up. It's easier to show here:

https://youtu.be/ozaZp3wS1Go

Note that I have reproduced this behaviour exactly the same way on a Windows 7 virtual machine, also with a clean install, so it does not seem to be OS-specific.

**Comment by bemilton** [comment]
First, thank you for a detailed video. Leave your path _relative_ as this is also how I've configured mine. 

For the issue of syntax, here are my user-specific configuration overrides. Try adding `color_scheme`, `extensions`, and `wiki_extensions` to yours. Then re-test.

```
{
	"csl_style": "/home/bemilton/gitstuff/styles/ieee.csl",
	"pane_for_opening_notes": 0,
	"pane_for_opening_results": 1,
	"venv_spacy_fk_abspath": "/home/bemilton/anaconda3/envs/sublime_zk/bin/python",
	"spacy_fk_script_abspath": "/home/bemilton/gitstuff/fkshelperscript",
	"bibfile": "/home/bemilton/Docs/library.bib",
	"wiki_extension": ".md",
	"extensions":
	[
		"md",
	],
	"id_in_title": false,
	"insert_tag_count": true,
	"insert_links_with_titles": true,
	"move_title_inside_brackets": true,
	"new_note_template": "---\nuid: {id}\ntitle: {title}\nauthor: \ndate: {timestamp: %Y-%m-%d %H:%M:%S}\nbacklink: {origin_id}\ntags: \nfk: \n---\n\n\n\n\n\n\n----",
	"path_to_ag": "/usr/bin/ag",
	"seconds_in_id": true,
	"toc_suffix_separator": "_",
	"color_scheme": "Packages/sublime_zk/Monokai Extended-zk.tmTheme"
}
```
I also agree there could be some logic here which is unclear, at least your video shows the [automatic method instructions](https://github.com/bemilton/sublime_zk#automatic-approach) are not adequate. And the manual method instructions don't work for you. Maybe my commits introduced this bug. When you follow the same instructions with the original author's version, is the result the same?

For my forked version, when that note failed to create at 1m30s it would have been useful to get a copy of the console output log (you can press `ctrl`+```).

**Comment by emilBeBri** [comment]
no problem, thanks for keeping this fantastic tool alive!! I'm having a busy week and will get back to it ASAP :)

**Comment by emilBeBri** [comment]
Sorry it's been a busy week. Did you close it because I didn't respond, or because you fixed it? I can try the things you suggested today.

**Comment by bemilton** [comment]
I will reopen the issue if the problem continues.
